name: frustchat
description: A premium venting chat application.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  provider: ^6.0.5
  file_picker: ^6.1.1
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  animations: ^2.0.11

flutter:
  uses-material-design: true
